@startuml

Instrumento <|-- Guitarra
Instrumento <|-- Saxo
Instrumento <|-- Tiple
Instrumento <|-- Bajo
Instrumento <|-- Maracas
Instrumento <|-- Arpa
Instrumento <|-- Acordeon
Instrumento <|-- Flauta
Instrumento <|-- Chelo
Instrumento <|-- Bateria


Musico *-- Instrumento
Banda *-- Instrumento

Instrumento : afinar()
Instrumento : tocar()

Musico : Instrumento
Musico : afinar_instrumento()
Musico : tocar_instrumento()

Banda : musicos
Banda : afinar()
Banda : tocar()
Banda : arma_banda()  


@enduml